<h1><center>Laboratorio 4: El Pandas no muerde (act. I) 🐼</center></h1>

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos</strong></center>

### Cuerpo Docente:

- Profesores: Ignacio Meza, Gabriel Iturra
- Auxiliar: Sebastián Tinoco
- Ayudante: Arturo Lazcano, Angelo Muñoz

### Equipo: SUPER IMPORTANTE - notebooks sin nombre no serán revisados

- Nombre de alumno 1: Sebastián Ojeda G.


### **Link de repositorio de GitHub:** https://github.com/sebajedi23/MDS7202

### Reglas:

- **Grupos de 2 personas**
- Asistencia **obligatoria** a instrucciones del lab (viernes 16.15). Luego, pueden quedarse trabajando en las salas o irse.
- **Ausentes tienen nota máxima 6.0**.
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Prohibidas las copias.
- Pueden usar cualquer matrial del curso que estimen conveniente.

### Temas a tratar

- Introducción al manejo de datos tabulares por medio de la libreria `pandas`.

### Objetivos principales del laboratorio

- Entender, aplicar y aprovechar las ventajas que nos ofrece la libreria `pandas` para manejar datos tabulares.
- Aprender a utilizar la documentación de pandas (y en general, de cualquier librería de python) como también a buscar soluciones en la web.

> **Nota**: El laboratorio deberá ser desarrollado sin el uso indiscriminado de iteradores nativos de python (aka "for", "while"). La idea es que aprendan a exprimir al máximo las funciones optimizadas que nos entrega `pandas`, las cuales vale mencionar, son bastante más eficientes que los iteradores nativos sobre DataFrames.

### Librerias utiles para el Lab 😸

In [42]:
# Libreria Core del lab.
import numpy as np
import pandas as pd
from IPython.display import display

#Libreria para plotear
!pip install --upgrade plotly
import plotly.express as px

# Librerias utiles
from sklearn.preprocessing import StandardScaler

# 1. Rendimiento en Estudiantes 📚

Para este laboratorio deberán trabajar con el dataset `students_grades.json` el cual contiene información sobre el rendimiento de alumnos en distintos ramos.
El objetivo principal será el de realizar un trabajo de limpieza de prepración y exploración de datos utilizando exclusivamente `DataFrames` y sus métodos asociados.




In [43]:
# Si usted está utilizando Colabolatory le puede ser útil este código para cargar los archivos.
try:
    from google.colab import drive
    drive.mount("/content/drive")
    path = '/content/drive/MyDrive/Colab Notebooks/Laboratorio de programación científica para ciencia de datos/students_grades.json'
except:
    print('Ignorando conexión drive-colab')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## 1.1 Carga e Inspección de Datos [1.5 Puntos]


<p align="center">
  <img src="https://drive.google.com/uc?export=view&id=1hZZaPQlZe4VupFOXt76_wjuUA5NpUhrw" width="300" height="300">
</p>


*Don Caguayo*, rector de la Universidad de la Cachaña, les comenta que actualmente la Universidad no tiene una subdirección de análisis de datos, pero que tiene un gran interés en formar una. Es por esto, que se contacta con ud. y su equipo para iniciar de forma exploratoria diversas tareas de análisis y consolidación de datos respectivos al rendimiento de sus alumnos.

Previo a su primera reunión con el rector, el rector le envía una copia de la base de datos, la cuál a usted y su equipo le encantaría examinar. Para esto, la primera tarea que debe realizar es abrir y cargar el dataset.


> **Notar que es sumamente importante el formato que posee cada columna** para su manipulación y que posiblemente ustedes deberán especificar algunos tipos de datos a mano. Ver la documentación del método `read_json` para mayor información.

A continuación se muestra un ejemplo de los dos primeros registros del dataset:

```json
[
  {
    "names": "Rita Courtney",
    "gender": "female",
    "race/ethnicity": "group B",
    "parental level of education": "some high school",
    "lunch": "standard",
    "test preparation course": "none",
    "math score": 37,
    "reading score": 46,
    "writing score": 46
  },
  {
    "names": "Madeline Fuller",
    "gender": "female",
    "race/ethnicity": "group C",
    "parental level of education": "some high school",
    "lunch": "standard",
    "test preparation course": "none",
    "math score": 124,
    "reading score": 142,
    "writing score": 142
  }
]
```





In [44]:
#Especificamos el tipo de dato que contienen las columnas
column_types = {
    "math score": int,
    "reading score": int,
    "writing score": int
}

#Creamos el dataframe a partir del archivo json
df_grades = pd.read_json(path, dtype=column_types)
df_grades

names  gender race/ethnicity parental level of education  \
0        Rita Courtney  female        group B            some high school   
1      Madeline Fuller  female        group C            some high school   
2        Daniel Rester    male        group E          associate's degree   
3     Charles Linstrom    male        group A           bachelor's degree   
4       Geraldine Hale  female        group A          associate's degree   
...                ...     ...            ...                         ...   
1395  Alexander Dillon    male        group D          associate's degree   
1396    Marina Zeigler  female        group C           bachelor's degree   
1397     Laurie Carter  female        group B            some high school   
1398      Joseph Mccoy    male        group D                some college   
1399      Amanda Perez  female        group A                 high school   

             lunch test preparation course math score reading score  \
0         standard                    none         37            46   
1         standard                    none        124           142   
2         standard                    none        156           196   
3         standard               completed         80            78   
4         standard                    none        131           166   
...            ...                     ...        ...           ...   
1395      standard                    none        193           142   
1396  free/reduced               completed         66            74   
1397      standard               completed         54            61   
1398  free/reduced                    none        193           196   
1399      standard               completed         68            80   

     writing score  
0               46  
1              142  
2              193  
3               81  
4              166  
...            ...  
1395           193  
1396            81  
1397            62  
1398           193  
1399            76  

[1400 rows x 9 columns]

In [45]:
#Reemplazamos los valores faltantes por NaN en las columnas de score
columns = ["math score", "reading score", "writing score"]
df_grades[columns] = df_grades[columns].replace('', np.nan)
df_grades

names  gender race/ethnicity parental level of education  \
0        Rita Courtney  female        group B            some high school   
1      Madeline Fuller  female        group C            some high school   
2        Daniel Rester    male        group E          associate's degree   
3     Charles Linstrom    male        group A           bachelor's degree   
4       Geraldine Hale  female        group A          associate's degree   
...                ...     ...            ...                         ...   
1395  Alexander Dillon    male        group D          associate's degree   
1396    Marina Zeigler  female        group C           bachelor's degree   
1397     Laurie Carter  female        group B            some high school   
1398      Joseph Mccoy    male        group D                some college   
1399      Amanda Perez  female        group A                 high school   

             lunch test preparation course  math score  reading score  \
0         standard                    none        37.0           46.0   
1         standard                    none       124.0          142.0   
2         standard                    none       156.0          196.0   
3         standard               completed        80.0           78.0   
4         standard                    none       131.0          166.0   
...            ...                     ...         ...            ...   
1395      standard                    none       193.0          142.0   
1396  free/reduced               completed        66.0           74.0   
1397      standard               completed        54.0           61.0   
1398  free/reduced                    none       193.0          196.0   
1399      standard               completed        68.0           80.0   

      writing score  
0              46.0  
1             142.0  
2             193.0  
3              81.0  
4             166.0  
...             ...  
1395          193.0  
1396           81.0  
1397           62.0  
1398          193.0  
1399           76.0  

[1400 rows x 9 columns]


<p align="center">
  <img src="https://i.giphy.com/media/4FQMuOKR6zQRO/giphy.webp">
</p>


Posteriormente, el rector les comenta que la sección de TI posee una base de datos con más de **875** filas, en donde cada fila representa un alumno matriculado. Sin embargo, cree fuertemente que existen errores en esta: solo tiene registro de **875** matriculas. Por este motivo, especula que se han realizado malas prácticas al registrar dichos datos.

En consecuencia, el rector les solicita a ustedes como tarea inicial que exploren la base de datos y encuentre posibles falencias dentro de sus registros. Para esto, usted debe estar al tanto que las notas están en una escala que van del **0 al 100** (porcentaje de logro) y **no es posible que un alumno haya dado más de una vez el mismo examen**. Cualquier alumno que posea un valor diferente a esta escala, debería ser eliminado de la base de datos.


> **Instrucciones**

**Cree una función** que tome un `DataFrame` y que le permita revisar si las diferentes variables que lo componen son coherentes y si es posible observar anomalías en estas.

**To-Do**
1. [ ] Imprimir un mensaje con las dimensiones del Dataframe.
2. [ ] Imprimir un mensaje con los nombres de las columnas que conforman el DataFrame.
3. [ ] Mostrar los primeros 5, los últimos 5 elementos del DataFrame y realice un muestreo de 5 elementos de forma aleatoria.
4. [ ] Mostrar una descripción rápida de las variables numéricas del DataFrame (utilice un método visto en clases).
5. [ ] Imprimir un mensaje con la cantidad de valores nulos (investigue el método `isna()` y `sum()` de los DataFrames).
6. [ ] Imprimir un mensaje que detalle la cantidad de valores unicos (investigue `nunique()`) .
7. [ ] Imprimir un mensaje con el total de filas que contengan nombres duplicados (investigue `duplicated()` y su parámetro `subset`).
8. [ ] Mostrar las filas que contengan nombres sean duplicados (investigue `duplicated()` y su parámetro `subset`).
9. [ ] A traves de `.plot.box()` plotear el boxplot de las notas. De ser necesario, invetigue como funcionan los gráficos de caja (esta sección es provista).
10. [ ] Finalmente responda la siguiente pregunta:

> ¿Que anomalias es posible observar de los datos que componen el DataFrame? ¿Existen valores nulos o duplicados? ¿Qué puede interpretar de la distribución de las notas en el boxplot? (), comente esto en la celda ubicada debajo de **justificación**.

> **Nota:** Para imprmir utilice `print(...)`. Para mostrar `DataFrames`, utilice `display(...)` ya que este permite mostrar estos elementos como tablas.

> **Nota 2:** Utilice la documentación de [pandas](https://pandas.pydata.org/docs/index.html) como también StackOverflow para resolver cualquier problema o inconveniente.

> **Nota 3:** Si no ha trabajado con boxplot antes, el siguiente link puede serle de mucha ayuda: [boxplot](https://medium.com/dayem-siddiqui/understanding-and-interpreting-box-plots-d07aab9d1b6c)

**Respuesta:**

In [46]:
def exploratory_data_analysis(dataframe):
    """Recibe un dataframe y entrega 9 puntos relevantes para su análisis

    Parameters
    ----------
    dataframe : pandas.core.frame.DataFrame
        Dataframe de pandas a analizar
    """
    # 1. Imprimir un mensaje con las dimensiones del Dataframe.
    print(f"1.- El DataFrame tiene {dataframe.shape[0]} filas y {dataframe.shape[1]} columnas\n")

    # 2. Imprimir un mensaje con los nombres de las columnas que conforman el
    # DataFrame.
    print(f"2.- El DataFrame está compuesto por las siguientes columnas: {(dataframe.columns.values)}\n")

    # 3. Mostrar los primeros 5, los últimos 5 elementos del DataFrame y realice
    # un muestreo de 5 elementos de forma aleatoria.
    print("3.- Ejemplos de filas del DataFrame:")
    print("\nPrimeras 5 filas:")
    display(df_grades.head())
    print("\nÚltimas 5 filas:")
    display(df_grades.tail())
    print("\nMuestreo aleatorio de 5 filas:")
    display(dataframe.sample(5))
    print("\n")

    # 4. Descripción numérica del DataFrame
    print("4.- Descripción numérica del Dataframe:")
    display(dataframe.describe())
    print("\n")

    # 5. Cantidad de valores nulos por columna
    print("5.- Cantidad de valores nulos por columna:")
    display(dataframe.isna().sum())
    print("\n")

    # 6. Cantidad de valores únicos por columna
    print("6.- Cantidad de valores únicos por columna:")
    display(dataframe.nunique())
    print("\n")

    # 7. Presenta un total de filas con nombres duplicados
    a = int(df_grades.duplicated(subset="names").sum())
    print(f"7.- Presenta un total de {a} filas con nombres duplicados.\n")

    # 8. Las filas con nombres duplicados
    print("8.- Las filas con nombres duplicados son:")
    display(dataframe[dataframe.duplicated(subset="names")])
    print("\n")

    # 9. Boxplot de notas utilizando Plotly Express
    print('9.- Boxplot de Notas')
    # Crear un DataFrame con las tres columnas a representar
    data = dataframe[["math score", "reading score", "writing score"]]

    # Derretir el DataFrame para tener una sola columna "score" y una columna "subject" para diferenciar las materias
    melted_data = pd.melt(data, var_name="subject", value_name="score")

    # Mostrar el boxplot de las notas, usando plotly
    fig = px.box(melted_data, y="score", color="subject")

    # Mostramos el boxplot
    fig.show()

In [47]:
exploratory_data_analysis(df_grades)

1.- El DataFrame tiene 1400 filas y 9 columnas

2.- El DataFrame está compuesto por las siguientes columnas: ['names' 'gender' 'race/ethnicity' 'parental level of education' 'lunch'
 'test preparation course' 'math score' 'reading score' 'writing score']

3.- Ejemplos de filas del DataFrame:

Primeras 5 filas:


names  gender race/ethnicity parental level of education  \
0     Rita Courtney  female        group B            some high school   
1   Madeline Fuller  female        group C            some high school   
2     Daniel Rester    male        group E          associate's degree   
3  Charles Linstrom    male        group A           bachelor's degree   
4    Geraldine Hale  female        group A          associate's degree   

      lunch test preparation course  math score  reading score  writing score  
0  standard                    none        37.0           46.0           46.0  
1  standard                    none       124.0          142.0          142.0  
2  standard                    none       156.0          196.0          193.0  
3  standard               completed        80.0           78.0           81.0  
4  standard                    none       131.0          166.0          166.0


Últimas 5 filas:


names  gender race/ethnicity parental level of education  \
1395  Alexander Dillon    male        group D          associate's degree   
1396    Marina Zeigler  female        group C           bachelor's degree   
1397     Laurie Carter  female        group B            some high school   
1398      Joseph Mccoy    male        group D                some college   
1399      Amanda Perez  female        group A                 high school   

             lunch test preparation course  math score  reading score  \
1395      standard                    none       193.0          142.0   
1396  free/reduced               completed        66.0           74.0   
1397      standard               completed        54.0           61.0   
1398  free/reduced                    none       193.0          196.0   
1399      standard               completed        68.0           80.0   

      writing score  
1395          193.0  
1396           81.0  
1397           62.0  
1398          193.0  
1399           76.0


Muestreo aleatorio de 5 filas:


names  gender race/ethnicity parental level of education  \
152      Rose Aiken  female        group B          associate's degree   
990   Lance Santana    male        group B            some high school   
463    Jeanine Diaz  female        group B           bachelor's degree   
1216   Robert Beard    male        group C                some college   
57    Tanya Freeman  female        group C          associate's degree   

             lunch test preparation course  math score  reading score  \
152       standard                    none       193.0            NaN   
990       standard                    none        68.0           54.0   
463       standard                    none        97.0           97.0   
1216      standard                    none        91.0           74.0   
57    free/reduced                    none       196.0          142.0   

      writing score  
152           124.0  
990            53.0  
463            96.0  
1216           76.0  
57            142.0



4.- Descripción numérica del Dataframe:


math score  reading score  writing score
count  1360.000000    1360.000000    1353.000000
mean     89.538971      93.086029      91.852919
std      47.152422      46.385775      47.043570
min       0.000000      17.000000      10.000000
25%      59.000000      63.000000      62.000000
50%      72.000000      76.000000      75.000000
75%      97.250000     100.000000     100.000000
max     196.000000     196.000000     196.000000



5.- Cantidad de valores nulos por columna:


names                           0
gender                          0
race/ethnicity                  0
parental level of education     0
lunch                           0
test preparation course         0
math score                     40
reading score                  40
writing score                  47
dtype: int64



6.- Cantidad de valores únicos por columna:


names                          1153
gender                            2
race/ethnicity                    5
parental level of education       6
lunch                             2
test preparation course           2
math score                       96
reading score                    88
writing score                    92
dtype: int64



7.- Presenta un total de 247 filas con nombres duplicados.

8.- Las filas con nombres duplicados son:


names  gender race/ethnicity parental level of education  \
12         Rita Courtney  female        group B            some high school   
81    Elizabeth Quintero  female        group B                some college   
160    Michelle Gonzales  female        group B            some high school   
170        Carla Mendoza  female        group D          associate's degree   
176       Darlene Parker  female        group C          associate's degree   
...                  ...     ...            ...                         ...   
1385      James Crawford    male        group D             master's degree   
1390     Gloria Bradford  female        group B                 high school   
1393         Adam Romero    male        group C                 high school   
1395    Alexander Dillon    male        group D          associate's degree   
1398        Joseph Mccoy    male        group D                some college   

             lunch test preparation course  math score  reading score  \
12        standard                    none       193.0          193.0   
81        standard                    none        82.0           85.0   
160       standard               completed        60.0           70.0   
170   free/reduced                    none        43.0           60.0   
176       standard                    none        54.0           61.0   
...            ...                     ...         ...            ...   
1385      standard                    none       193.0          147.0   
1390      standard                    none       124.0           64.0   
1393      standard               completed       124.0          193.0   
1395      standard                    none       193.0          142.0   
1398  free/reduced                    none       193.0          196.0   

      writing score  
12            193.0  
81             87.0  
160            74.0  
170            58.0  
176            58.0  
...             ...  
1385          131.0  
1390          193.0  
1393           49.0  
1395          193.0  
1398          193.0  

[247 rows x 9 columns]



9.- Boxplot de Notas


**Justificación:**

```
Según lo visto anteriormente, no concuerdan las 1400 filas y los 1153 nombres únicos con las 875 matrículas que se tienen.

Además, se puede ver que las notas llegan hasta 196 cuando la escala debería llegar hasta 100, por lo que según lo indicado, estos
alumnos no deberían estar en la base de datos.

Al analizar los boxplot se ve que el cuartil 3 de las tres variables score está cercano a 100 y el cuartil 4 está cercano a 150,
por lo que es de esperarse que aproximadamente el 25% de los datos estén por sobre el valor máximo de la escala y por ende sean
erróneos.

En conclusión, es claro que se han realizado malas prácticas en la base de datos, teniéndose registros duplicados, notas fuera
de la escala y valores nulos en varias de las filas.
```

**Respuesta Esperada:**

In [ ]:
exploratory_data_analysis(df_grades)

1.- El DataFrame tiene 1400 filas y 9 columnas

2.- El DataFrame esta compuesto por las siguientes columnas: ['names', 'gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']

3.- Ejemplos de filas del DataFrame:

Primeras 5 filas:


names  gender race/ethnicity parental level of education  \
0     Rita Courtney  female        group B            some high school   
1   Madeline Fuller  female        group C            some high school   
2     Daniel Rester    male        group E          associate's degree   
3  Charles Linstrom    male        group A           bachelor's degree   
4    Geraldine Hale  female        group A          associate's degree   

      lunch test preparation course  math score  reading score  writing score  
0  standard                    none        37.0           46.0           46.0  
1  standard                    none       124.0          142.0          142.0  
2  standard                    none       156.0          196.0          193.0  
3  standard               completed        80.0           78.0           81.0  
4  standard                    none       131.0          166.0          166.0


Últimas 5 filas:


names  gender race/ethnicity parental level of education  \
1395  Alexander Dillon    male        group D          associate's degree   
1396    Marina Zeigler  female        group C           bachelor's degree   
1397     Laurie Carter  female        group B            some high school   
1398      Joseph Mccoy    male        group D                some college   
1399      Amanda Perez  female        group A                 high school   

             lunch test preparation course  math score  reading score  \
1395      standard                    none       193.0          142.0   
1396  free/reduced               completed        66.0           74.0   
1397      standard               completed        54.0           61.0   
1398  free/reduced                    none       193.0          196.0   
1399      standard               completed        68.0           80.0   

      writing score  
1395          193.0  
1396           81.0  
1397           62.0  
1398          193.0  
1399           76.0


Muestreo aleatorio de 5 filas:


names  gender race/ethnicity parental level of education  \
1282  Alberto Roberts    male        group D          associate's degree   
604     Ronald Wilson    male        group C            some high school   
559    Christine Reed  female        group E           bachelor's degree   
380      Edna Johnson  female        group E                some college   
1392    Richard Young    male        group D                 high school   

         lunch test preparation course  math score  reading score  \
1282  standard                    none        52.0           55.0   
604   standard                    none        64.0           58.0   
559   standard               completed       188.0          142.0   
380   standard               completed       193.0          124.0   
1392  standard                    none        69.0           75.0   

      writing score  
1282           49.0  
604            51.0  
559           131.0  
380           196.0  
1392           71.0


4.- Descripción numérica del Dataframe:


math score  reading score  writing score
count  1360.000000    1360.000000    1353.000000
mean     89.538971      93.086029      91.852919
std      47.152422      46.385775      47.043570
min       0.000000      17.000000      10.000000
25%      59.000000      63.000000      62.000000
50%      72.000000      76.000000      75.000000
75%      97.250000     100.000000     100.000000
max     196.000000     196.000000     196.000000


5.- Cantidad de valores nulos por columna:


names                           0
gender                          0
race/ethnicity                  0
parental level of education     0
lunch                           0
test preparation course         0
math score                     40
reading score                  40
writing score                  47
dtype: int64


6.- Cantidad de valores únicos por columna:


names                          1153
gender                            2
race/ethnicity                    5
parental level of education       6
lunch                             2
test preparation course           2
math score                       96
reading score                    88
writing score                    92
dtype: int64


7.- Presenta un total de 247 filas con nombres duplicados.

8.- Las filas con nombres duplicados son:


names  gender race/ethnicity parental level of education  \
12         Rita Courtney  female        group B            some high school   
81    Elizabeth Quintero  female        group B                some college   
160    Michelle Gonzales  female        group B            some high school   
170        Carla Mendoza  female        group D          associate's degree   
176       Darlene Parker  female        group C          associate's degree   
...                  ...     ...            ...                         ...   
1385      James Crawford    male        group D             master's degree   
1390     Gloria Bradford  female        group B                 high school   
1393         Adam Romero    male        group C                 high school   
1395    Alexander Dillon    male        group D          associate's degree   
1398        Joseph Mccoy    male        group D                some college   

             lunch test preparation course  math score  reading score  \
12        standard                    none       193.0          193.0   
81        standard                    none        82.0           85.0   
160       standard               completed        60.0           70.0   
170   free/reduced                    none        43.0           60.0   
176       standard                    none        54.0           61.0   
...            ...                     ...         ...            ...   
1385      standard                    none       193.0          147.0   
1390      standard                    none       124.0           64.0   
1393      standard               completed       124.0          193.0   
1395      standard                    none       193.0          142.0   
1398  free/reduced                    none       193.0          196.0   

      writing score  
12            193.0  
81             87.0  
160            74.0  
170            58.0  
176            58.0  
...             ...  
1385          131.0  
1390          193.0  
1393           49.0  
1395          193.0  
1398          193.0  

[247 rows x 9 columns]


9.- Boxplot de notas:


## 1.2 Limpieza de Datos [1 punto]

<p align="center">
  <img src="https://blogdatlas.files.wordpress.com/2020/07/datlas_mx_blog_limpieza_bds_data-scrubbing-service.gif">
</p>


En base a lo realizado anteriormente, realice una limpieza de los dataset. Asuma los supuestos señalados en la pregunta anterior para limpiar el `DataFrame` y cree una función que le permita limpiar los datos. Habiendo limpiado el `DataFrame`, compruebe nuevamente los datos con la función creada en la sección 1.1.

**To-Do:**

- [ ] Crear función que permita limpiar el dataset.
- [ ] Comprobar que no existen anomalías en los datos a traves de la función de la sección 1.1.

**Hint**

Puede ser útil los métodos ```.drop_duplicates()``` y ```.dropna()``` como también utilizar queries con máscaras booleanas.


**Respuesta:**

In [49]:
def clean_data(df):
    """Limpia un dataframe de entradas repetidas o valores inexistentes o fuera
    de la escala de notas

    Parameters
    ----------
    df : pandas.core.frame.DataFrame
        Dataframe a limpiar
    """

    #Primero eliminamos las notas fuera de la escala
    df = df[(df["math score"] >= 0) & (df["math score"] <= 100)]
    df = df[(df["reading score"] >= 0) & (df["reading score"] <= 100)]
    df = df[(df["writing score"] >= 0) & (df["writing score"] <= 100)]

    #Luego eliminamos las entradas duplicadas por nombre
    df = df.drop_duplicates(subset="names")

    #Eliminamos las entradas nulas
    df = df.dropna()

    #Finalmente reseteamos los índices para que no haya saltos debido a las
    #filas eliminadas
    df = df.reset_index(drop=True)

    return df

In [50]:
df_grades = clean_data(df_grades)
df_grades

names  gender race/ethnicity parental level of education  \
0       Rita Courtney  female        group B            some high school   
1    Charles Linstrom    male        group A           bachelor's degree   
2         Brian Young    male        group C            some high school   
3      Howard Jimenez    male        group E            some high school   
4        Wayne Wilson    male        group B            some high school   
..                ...     ...            ...                         ...   
995     Richard Young    male        group D                 high school   
996     Wanda Russell  female        group B                 high school   
997    Marina Zeigler  female        group C           bachelor's degree   
998     Laurie Carter  female        group B            some high school   
999      Amanda Perez  female        group A                 high school   

            lunch test preparation course  math score  reading score  \
0        standard                    none        37.0           46.0   
1        standard               completed        80.0           78.0   
2        standard                    none        73.0           66.0   
3        standard               completed        81.0           75.0   
4        standard               completed        94.0           86.0   
..            ...                     ...         ...            ...   
995      standard                    none        69.0           75.0   
996  free/reduced               completed        23.0           44.0   
997  free/reduced               completed        66.0           74.0   
998      standard               completed        54.0           61.0   
999      standard               completed        68.0           80.0   

     writing score  
0             46.0  
1             81.0  
2             63.0  
3             76.0  
4             87.0  
..             ...  
995           71.0  
996           36.0  
997           81.0  
998           62.0  
999           76.0  

[1000 rows x 9 columns]

> Utilice la función creada en el punto 1.1 para verificar sus resultados.

In [51]:
exploratory_data_analysis(df_grades)

1.- El DataFrame tiene 1000 filas y 9 columnas

2.- El DataFrame está compuesto por las siguientes columnas: ['names' 'gender' 'race/ethnicity' 'parental level of education' 'lunch'
 'test preparation course' 'math score' 'reading score' 'writing score']

3.- Ejemplos de filas del DataFrame:

Primeras 5 filas:


names  gender race/ethnicity parental level of education  \
0     Rita Courtney  female        group B            some high school   
1  Charles Linstrom    male        group A           bachelor's degree   
2       Brian Young    male        group C            some high school   
3    Howard Jimenez    male        group E            some high school   
4      Wayne Wilson    male        group B            some high school   

      lunch test preparation course  math score  reading score  writing score  
0  standard                    none        37.0           46.0           46.0  
1  standard               completed        80.0           78.0           81.0  
2  standard                    none        73.0           66.0           63.0  
3  standard               completed        81.0           75.0           76.0  
4  standard               completed        94.0           86.0           87.0


Últimas 5 filas:


names  gender race/ethnicity parental level of education  \
995   Richard Young    male        group D                 high school   
996   Wanda Russell  female        group B                 high school   
997  Marina Zeigler  female        group C           bachelor's degree   
998   Laurie Carter  female        group B            some high school   
999    Amanda Perez  female        group A                 high school   

            lunch test preparation course  math score  reading score  \
995      standard                    none        69.0           75.0   
996  free/reduced               completed        23.0           44.0   
997  free/reduced               completed        66.0           74.0   
998      standard               completed        54.0           61.0   
999      standard               completed        68.0           80.0   

     writing score  
995           71.0  
996           36.0  
997           81.0  
998           62.0  
999           76.0


Muestreo aleatorio de 5 filas:


names  gender race/ethnicity parental level of education  \
839      Michael Diaz    male        group E          associate's degree   
83     Vickie Sellers  female        group D                some college   
171   Michael Mederos    male        group C                 high school   
867  Thomas Whitehead    male        group D                 high school   
574       Julie Lopez  female        group E                some college   

        lunch test preparation course  math score  reading score  \
839  standard                    none        87.0           74.0   
83   standard               completed        68.0           78.0   
171  standard                    none        50.0           48.0   
867  standard               completed        68.0           64.0   
574  standard               completed        73.0           78.0   

     writing score  
839           76.0  
83            77.0  
171           42.0  
867           66.0  
574           76.0



4.- Descripción numérica del Dataframe:


math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000



5.- Cantidad de valores nulos por columna:


names                          0
gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64



6.- Cantidad de valores únicos por columna:


names                          1000
gender                            2
race/ethnicity                    5
parental level of education       6
lunch                             2
test preparation course           2
math score                       81
reading score                    72
writing score                    77
dtype: int64



7.- Presenta un total de 0 filas con nombres duplicados.

8.- Las filas con nombres duplicados son:


Empty DataFrame
Columns: [names, gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score]
Index: []



9.- Boxplot de Notas


**Justificación:**

```
Se puede decir que la limpieza fue satisfactoria, ya que al realizar el análisis del dataframe después de limpiarlo se observa que
las notas están en su totalidad contenidas dentro del rango [0,100], además de que ya no se tienen valores nulos ni filas duplicadas, por esto mismo, los nombres ahora son todos únicos.

Debido a la limpieza, se borraron 400 registros debido a diversos errores que contenían, dejando así el dataframe con 1000 filas
y 9 columnas.
```

## 1.3 Trabajando con Datos

<p align="center">
  <img src="https://media3.giphy.com/media/YQitE4YNQNahy/giphy-downsized-large.gif">
</p>

### 1.3.1 Transformación de notas a "Nota Chilena" [0.5 Puntos]

En una de las reuniones con Don Caguayo este les comenta su intención de pasar todas sus notas a la "Escala Chilena". Para esto les facilita la siguiente ecuación:

$$Nota \, Chilena= \% \, de \, logro*0.06 + 1$$

Utilizando la ecuación entregada, cree una función que le permita pasar a la escala Chilena las notas del dataframe y entregue las notas redondeadas al segundo decimal.

**To-Do**

- [ ] Tranforme los valores a la escala chilena.

**Respuesta:**

In [52]:
def nota_chilena(dataframe_in, columna):
    """Convierte las notas de una columna de escala estadounidense a chilena
    redondeadas al segundo decimal

    Parameters
    ----------
    dataframe_in : pandas.core.frame.DataFrame
        Dataframe de pandas al que se quiere transformar las notas
    columna : str
        Nombre de la columna del dataframe a transformar
    """
    #Usamos la fórmula dada para convertir las notas de la columna en cuestión
    dataframe_in[columna] = dataframe_in[columna].apply(lambda x: round(x * 0.06 + 1, 2))
    return dataframe_in

In [53]:
#Aplicamos la función a las tres columnas deseadas
nota_chilena(df_grades, "math score")
nota_chilena(df_grades, "reading score")
nota_chilena(df_grades, "writing score")

names  gender race/ethnicity parental level of education  \
0       Rita Courtney  female        group B            some high school   
1    Charles Linstrom    male        group A           bachelor's degree   
2         Brian Young    male        group C            some high school   
3      Howard Jimenez    male        group E            some high school   
4        Wayne Wilson    male        group B            some high school   
..                ...     ...            ...                         ...   
995     Richard Young    male        group D                 high school   
996     Wanda Russell  female        group B                 high school   
997    Marina Zeigler  female        group C           bachelor's degree   
998     Laurie Carter  female        group B            some high school   
999      Amanda Perez  female        group A                 high school   

            lunch test preparation course  math score  reading score  \
0        standard                    none        3.22           3.76   
1        standard               completed        5.80           5.68   
2        standard                    none        5.38           4.96   
3        standard               completed        5.86           5.50   
4        standard               completed        6.64           6.16   
..            ...                     ...         ...            ...   
995      standard                    none        5.14           5.50   
996  free/reduced               completed        2.38           3.64   
997  free/reduced               completed        4.96           5.44   
998      standard               completed        4.24           4.66   
999      standard               completed        5.08           5.80   

     writing score  
0             3.76  
1             5.86  
2             4.78  
3             5.56  
4             6.22  
..             ...  
995           5.26  
996           3.16  
997           5.86  
998           4.72  
999           5.56  

[1000 rows x 9 columns]

### 1.3.2 Obtención de promedio de alumnos [0.5]

Con todas las notas adjuntadas, la prestigiosa Universidad De la Cachaña necesita obtener el promedio general de cada uno de los alumnos. Para esto se le solicita que calcule el promedio con cada una de las asignaturas y el promedio se anexe como una nueva columna al final del `DataFrame` original. Cabe señalar que las notas deben ser redondeadas al segundo decimal.

**To-Do:**
- [ ] Crear función que nos permite obtener el promedio de cada uno de los alumnos y anexar esta información en el `DataFrame` original.


**Respuesta:**

In [54]:
def alumnos_promedio(dataframe_in):
  """Obtiene el promedio de notas para un individuo en el dataframe y lo anexa
  en la columna GPA

  Parameters
  ----------
  dataframe_in : pandas.core.frame.DataFrame
      Dataframe de pandas al que se quiere calcular los promedios de notas
  """
  #Creamos una nueva columna con el promedio de las notas
  dataframe_in["GPA"] = dataframe_in[["math score", "reading score", "writing score"]].mean(axis=1)
  return dataframe_in

In [55]:
alumnos_promedio(df_grades)
df_grades.head()

names  gender race/ethnicity parental level of education  \
0     Rita Courtney  female        group B            some high school   
1  Charles Linstrom    male        group A           bachelor's degree   
2       Brian Young    male        group C            some high school   
3    Howard Jimenez    male        group E            some high school   
4      Wayne Wilson    male        group B            some high school   

      lunch test preparation course  math score  reading score  writing score  \
0  standard                    none        3.22           3.76           3.76   
1  standard               completed        5.80           5.68           5.86   
2  standard                    none        5.38           4.96           4.78   
3  standard               completed        5.86           5.50           5.56   
4  standard               completed        6.64           6.16           6.22   

    GPA  
0  3.58  
1  5.78  
2  5.04  
3  5.64  
4  6.34

**Respuesta Esperada:**

In [ ]:
df_grades = alumnos_promedio(df_grades)
df_grades.head()

names  gender race/ethnicity parental level of education  \
0     Rita Courtney  female        group B            some high school   
1  Charles Linstrom    male        group A           bachelor's degree   
2       Brian Young    male        group C            some high school   
3    Howard Jimenez    male        group E            some high school   
4      Wayne Wilson    male        group B            some high school   

      lunch test preparation course  math score  reading score  writing score  \
0  standard                    none        3.22           3.76           3.76   
1  standard               completed        5.80           5.68           5.86   
2  standard                    none        5.38           4.96           4.78   
3  standard               completed        5.86           5.50           5.56   
4  standard               completed        6.64           6.16           6.22   

    GPA  
0  3.58  
1  5.78  
2  5.04  
3  5.64  
4  6.34

### 1.3.3 Reprobados y Destacados [1.5 Punto, 0.5 Cada DataFrame]

Contentos con su desempeño, la Universidad les solicita que obtengan los alumnos quienes han reprobado el año y los que han tenido desempeño de destacado. Para esto se considerará que un alumno ha reprobado el año cuando el promedio de notas es inferior a 4.0 en la Escala Chilena, y se considerará destacado si posee notas superiores a 5.8 en todas las asignaturas (o sea notas superiores a 5.8 en `math score`, `reading score` y `writing score`).

Cree una función que permita obtener tres Dataframes:
- El primero deberá poseer solamente los alumnos que han reprobado en la prestigiosa universidad.
- El segundo debe entregar un DataFrame similar al original, pero marcado con una "R" el promedio de notas de los alumnos reprobados.
- El tercero será un Data Frame con los alumnos destacados ordenados de mayor a menor.

**To-Do:**

- [ ] Obtener DataFrame con los alumnos que reprobaron el año.
- [ ] Obtener DataFrame similar al original, pero marcados con una "R" el atributo GPA de los alumnos reprobados.
- [ ] Obtener DataFrame con los alumnos destacados ordenados de mayor a menor.

**Respuesta:**

In [56]:
def reprobados_destacados(dataframe_in):
    """Analiza los promedios de un dataframe y entrega 3 dataframes nuevos, uno
    con los alumnos reprobados, otro como el original pero indicando promedio R
    en los reprobados y otro con los alumnos destacados ordenados de mayor a
    menor.

    Parameters
    ----------
    dataframe_in : pandas.core.frame.DataFrame
        Dataframe de pandas a analizar
    """
    #Creamos un dataframe únicamente de los alumnos que tienen promedio menor a 4
    df_reprobados = dataframe_in[dataframe_in["GPA"] < 4.0]


    #Creamos un dataframe igual al inicial que cambia el valor de la columna GPA
    #por R si el promedio es menor a 4

    #Copiamos el dataframe
    df_R = dataframe_in.copy()

    #Cambiamos los promedio inferiores a 4 por R y mantenemos los demás
    df_R["GPA"] = df_R["GPA"].apply(lambda x: x if x >= 4.0 else "R")


    #Creamos un dataframe únicamente de los alumnos que tienen todas sus notas
    #mayores a 5.8
    df_destacados = dataframe_in[(dataframe_in["math score"] > 5.8) & (dataframe_in["reading score"] > 5.8) & (dataframe_in["writing score"] > 5.8)]
    #Ordenamos los promedios de mayor a menor
    df_destacados = df_destacados.sort_values(by = "GPA", ascending = False)

    #Retornamos los dataframes creados anteriormente
    return df_reprobados, df_R, df_destacados

In [57]:
dataframe1, dataframe2, dataframe3 = reprobados_destacados(df_grades)
dataframe1

names  gender race/ethnicity parental level of education  \
0      Rita Courtney  female        group B            some high school   
7        Mikki Amaya  female        group A                 high school   
16     Samuel Dougal    male        group C             master's degree   
39   Rodger Talavera    male        group B                 high school   
43    Morris Johnson    male        group A          associate's degree   
..               ...     ...            ...                         ...   
977   Charles Harian    male        group C            some high school   
979    Wendy Gunnell  female        group D            some high school   
993      Diana Costa  female        group C                 high school   
994      Amy Sieving  female        group C                 high school   
996    Wanda Russell  female        group B                 high school   

            lunch test preparation course  math score  reading score  \
0        standard                    none        3.22           3.76   
7    free/reduced               completed        3.04           3.88   
16   free/reduced               completed        3.76           3.52   
39   free/reduced                    none        3.16           2.74   
43   free/reduced               completed        3.40           4.30   
..            ...                     ...         ...            ...   
977  free/reduced               completed        3.70           4.12   
979  free/reduced                    none        2.62           3.04   
993  free/reduced                    none        3.46           3.76   
994      standard                    none        2.74           2.74   
996  free/reduced               completed        2.38           3.64   

     writing score   GPA  
0             3.76  3.58  
7             3.46  3.46  
16            3.76  3.68  
39            2.62  2.84  
43            4.18  3.96  
..             ...   ...  
977           3.94  3.92  
979           2.92  2.86  
993           3.58  3.60  
994           2.80  2.76  
996           3.16  3.06  

[103 rows x 10 columns]

In [58]:
dataframe2

names  gender race/ethnicity parental level of education  \
0       Rita Courtney  female        group B            some high school   
1    Charles Linstrom    male        group A           bachelor's degree   
2         Brian Young    male        group C            some high school   
3      Howard Jimenez    male        group E            some high school   
4        Wayne Wilson    male        group B            some high school   
..                ...     ...            ...                         ...   
995     Richard Young    male        group D                 high school   
996     Wanda Russell  female        group B                 high school   
997    Marina Zeigler  female        group C           bachelor's degree   
998     Laurie Carter  female        group B            some high school   
999      Amanda Perez  female        group A                 high school   

            lunch test preparation course  math score  reading score  \
0        standard                    none        3.22           3.76   
1        standard               completed        5.80           5.68   
2        standard                    none        5.38           4.96   
3        standard               completed        5.86           5.50   
4        standard               completed        6.64           6.16   
..            ...                     ...         ...            ...   
995      standard                    none        5.14           5.50   
996  free/reduced               completed        2.38           3.64   
997  free/reduced               completed        4.96           5.44   
998      standard               completed        4.24           4.66   
999      standard               completed        5.08           5.80   

     writing score   GPA  
0             3.76     R  
1             5.86  5.78  
2             4.78  5.04  
3             5.56  5.64  
4             6.22  6.34  
..             ...   ...  
995           5.26   5.3  
996           3.16     R  
997           5.86  5.42  
998           4.72  4.54  
999           5.56  5.48  

[1000 rows x 10 columns]

In [59]:
dataframe3

names  gender race/ethnicity parental level of education  \
267  Elizabeth Beasley  female        group E           bachelor's degree   
466      Richard Pryor    male        group E           bachelor's degree   
960      Sandra Pompey  female        group E          associate's degree   
332          Emma Gray  female        group E           bachelor's degree   
902     Angela Cressey  female        group D                some college   
..                 ...     ...            ...                         ...   
670     Rolando Widmer    male        group C                 high school   
203  Lucille Stanphill  female        group C                 high school   
206       Steven Kelly    male        group D                some college   
927        Peter Perez    male        group D             master's degree   
65         Harry Berry    male        group B          associate's degree   

        lunch test preparation course  math score  reading score  \
267  standard                    none        7.00           7.00   
466  standard               completed        7.00           7.00   
960  standard                    none        7.00           7.00   
332  standard               completed        6.94           7.00   
902  standard                    none        6.88           7.00   
..        ...                     ...         ...            ...   
670  standard               completed        5.92           6.04   
203  standard                    none        5.86           6.04   
206  standard                    none        5.86           5.92   
927  standard                    none        5.86           5.86   
65   standard               completed        5.86           5.92   

     writing score   GPA  
267           7.00  7.00  
466           7.00  7.00  
960           7.00  7.00  
332           7.00  6.98  
902           6.94  6.94  
..             ...   ...  
670           5.92  5.96  
203           5.92  5.94  
206           6.04  5.94  
927           6.04  5.92  
65            5.92  5.90  

[110 rows x 10 columns]

**Respuesta Esperada:**

In [ ]:
dataframe1, dataframe2, dataframe3 = reprobados_destacados(df_grades)
dataframe1

names  gender race/ethnicity parental level of education  \
0     Rita Courtney  female        group B            some high school   
1       Mikki Amaya  female        group A                 high school   
2     Samuel Dougal    male        group C             master's degree   
3   Rodger Talavera    male        group B                 high school   
4    Morris Johnson    male        group A          associate's degree   
..              ...     ...            ...                         ...   
81   Charles Harian    male        group C            some high school   
82    Wendy Gunnell  female        group D            some high school   
83      Diana Costa  female        group C                 high school   
84      Amy Sieving  female        group C                 high school   
85    Wanda Russell  female        group B                 high school   

           lunch test preparation course  math score  reading score  \
0       standard                    none        3.22           3.76   
1   free/reduced               completed        3.04           3.88   
2   free/reduced               completed        3.76           3.52   
3   free/reduced                    none        3.16           2.74   
4   free/reduced               completed        3.40           4.30   
..           ...                     ...         ...            ...   
81  free/reduced               completed        3.70           4.12   
82  free/reduced                    none        2.62           3.04   
83  free/reduced                    none        3.46           3.76   
84      standard                    none        2.74           2.74   
85  free/reduced               completed        2.38           3.64   

    writing score   GPA  
0            3.76  3.58  
1            3.46  3.46  
2            3.76  3.68  
3            2.62  2.84  
4            4.18  3.96  
..            ...   ...  
81           3.94  3.92  
82           2.92  2.86  
83           3.58  3.60  
84           2.80  2.76  
85           3.16  3.06  

[86 rows x 10 columns]

In [ ]:
dataframe2

names  gender race/ethnicity parental level of education  \
0       Rita Courtney  female        group B            some high school   
1    Charles Linstrom    male        group A           bachelor's degree   
2         Brian Young    male        group C            some high school   
3      Howard Jimenez    male        group E            some high school   
4        Wayne Wilson    male        group B            some high school   
..                ...     ...            ...                         ...   
870     Richard Young    male        group D                 high school   
871     Wanda Russell  female        group B                 high school   
872    Marina Zeigler  female        group C           bachelor's degree   
873     Laurie Carter  female        group B            some high school   
874      Amanda Perez  female        group A                 high school   

            lunch test preparation course  math score  reading score  \
0        standard                    none        3.22           3.76   
1        standard               completed        5.80           5.68   
2        standard                    none        5.38           4.96   
3        standard               completed        5.86           5.50   
4        standard               completed        6.64           6.16   
..            ...                     ...         ...            ...   
870      standard                    none        5.14           5.50   
871  free/reduced               completed        2.38           3.64   
872  free/reduced               completed        4.96           5.44   
873      standard               completed        4.24           4.66   
874      standard               completed        5.08           5.80   

     writing score   GPA  
0             3.76     R  
1             5.86  5.78  
2             4.78  5.04  
3             5.56  5.64  
4             6.22  6.34  
..             ...   ...  
870           5.26   5.3  
871           3.16     R  
872           5.86  5.42  
873           4.72  4.54  
874           5.56  5.48  

[875 rows x 10 columns]

In [ ]:
dataframe3

names  gender race/ethnicity parental level of education  \
0       Richard Pryor    male        group E           bachelor's degree   
1       Sandra Pompey  female        group E          associate's degree   
2   Elizabeth Beasley  female        group E           bachelor's degree   
3           Emma Gray  female        group E           bachelor's degree   
4        Emma Brasher  female        group D            some high school   
..                ...     ...            ...                         ...   
89     Rolando Widmer    male        group C                 high school   
90  Lucille Stanphill  female        group C                 high school   
91       Steven Kelly    male        group D                some college   
92        Peter Perez    male        group D             master's degree   
93        Harry Berry    male        group B          associate's degree   

       lunch test preparation course  math score  reading score  \
0   standard               completed        7.00           7.00   
1   standard                    none        7.00           7.00   
2   standard                    none        7.00           7.00   
3   standard               completed        6.94           7.00   
4   standard               completed        6.82           7.00   
..       ...                     ...         ...            ...   
89  standard               completed        5.92           6.04   
90  standard                    none        5.86           6.04   
91  standard                    none        5.86           5.92   
92  standard                    none        5.86           5.86   
93  standard               completed        5.86           5.92   

    writing score   GPA  
0            7.00   7.0  
1            7.00   7.0  
2            7.00   7.0  
3            7.00  6.98  
4            7.00  6.94  
..            ...   ...  
89           5.92  5.96  
90           5.92  5.94  
91           6.04  5.94  
92           6.04  5.92  
93           5.92   5.9  

[94 rows x 10 columns]

**Respuesta:**

```
Se puede ver que existen 103 alumnos reprobados (promedio menor a 4) y 110 destacados (todas las notas mayores a 5.8), además, como
es de esperarse, el dataframe 2 mantiene las 1000 filas del dataframe original.
```

### 1.3.4 Consultas de Alumnos [0.5 Puntos]

Algunos padres (extremadamente entrometidos y...) preocupados por el desempeño de sus hijos, desean saber estos han aprobado o no el año. Como la tarea de buscar a mano cada uno de estos alumnos en el `DataFrame` resulta demasiado tedioso, el rector le solicita crear una función que tenga como entrada el `DataFrame` donde se realizará la busqueda y una lista con los nombres de los alumnos, luego la función deberá retornar un `DataFrame` con los nombres de los alumnos y el promedio general de cada uno.

Creada la función busque el promedio general de los siguientes alumnos en el segundo Data frame creado en la sección 1.3.3:

`['Lucille Stanphill','Marcus Mcfarland', 'Matthew Freeman', 'Dana Mojica', 'Paul Hyder', 'Jeffrey Korn', 'Robert Strain',
'Ronald Jett', 'Lorena Reed', 'Hazel Posey']`

**Hint:** Puede serle de utilidad utilizar `isin()`.

**Respuesta:**

In [60]:
def consulta_gpa(dataframe_in, lista_alumnos):
    """Entrega un dataframe con los nombres y los promedios de una serie de
    alumnos a buscar en el dataframe de entrada.

    Parameters
    ----------
    dataframe_in : pandas.core.frame.DataFrame
        Dataframe de pandas a analizar
    lista_alumnos : list
        Lista con los nombres de los alumnos a consultar
    """
    #Creamos un dataframe para los nombres que aparecen en la lista de consulta
    #y sus respectivos promedios
    alumnos = dataframe_in[dataframe_in["names"].isin(lista_alumnos)][["names", "GPA"]]
    return alumnos


lista_alumnos = [
    "Lucille Stanphill",
    "Marcus Mcfarland",
    "Matthew Freeman",
    "Dana Mojica",
    "Paul Hyder",
    "Jeffrey Korn",
    "Robert Strain",
    "Ronald Jett",
    "Lorena Reed",
    "Hazel Posey",
]
consulta_gpa(dataframe2, lista_alumnos)

names   GPA
203  Lucille Stanphill  5.94
396   Marcus Mcfarland  4.86
446    Matthew Freeman     R
449        Dana Mojica     R
604         Paul Hyder   6.2
647       Jeffrey Korn  4.54
748      Robert Strain   4.4
752        Ronald Jett     R
754        Hazel Posey     R
849        Lorena Reed     R

### 1.3.5 Quintiles de Rendimiento [0.5 Puntos]

El rector, intrigado por saber si existe una relación entre el nivel educacional de los padres y las notas de sus hijos les plantea estudiar dicha relación. Para esto, les solicita que desde el `DataFrame` que posee a todos los alumnos (`DataFrame` obtenido tras la limpieza), generen una nueva columna que clasifique en quintiles de rendimiento para sus alumnos: `['Bajísimo', 'Bajo', 'Medio', 'Alto', 'Muy alto']`. (investigar `qcut()`)

Hecho esto, grafique a través de un scatter plot el nivel educacional de los padres v/s el promedio de los alumnos, utilice los cuantiles generados anteriormente para mostrar en que cuantil se encuentra cada uno de los datos.

Realizado el grafico, responda la siguiente pregunta: **¿Es posible visualizar alguna tendencia en el gráfico?.**



**Respuesta:**

In [61]:
# Código para quintiles
#Definimos GPA cuantiles de acuerdo a lo mostrado en el gráfico de ejemplo, se
#definen las etiquetas en orden ascendente.
df_grades["GPA cuantiles"] = pd.qcut(df_grades["GPA"], 5, labels=["Bajísimo", "Bajo", "Medio", "Alto", "Muy alto"])


# Código de gráfico
fig = px.scatter(
    df_grades.sort_values(by="GPA"),
    x="GPA",
    y="parental level of education",
    hover_data=["gender"],
    color="GPA cuantiles",
    title="GPA por Nivel de educación de los padres",
    color_discrete_sequence=["tomato", "orange", "yellow", "greenyellow", "green"]
)

fig

**Respuesta esperada:**

In [ ]:
# Código para quintiles
# La variable que contenga los quintiles debe llamarse GPA cuantiles para que el gráfico funcione.

# Código de gráfico
fig = px.scatter(
    df_grades.sort_values(by="GPA"),
    x="GPA",
    y="parental level of education",
    hover_data=["gender"],
    color="GPA cuantiles",
    title="GPA por Nivel de educación de los padres",
    color_discrete_sequence=["tomato", "orange", "yellow", "greenyellow", "green"]
)

fig


```
A partir del análisis del gráfico se puede apreciar una relación entre el nivel educacional de los padres y las notas de los hijos,
donde a mayor nivel educacional poseen los padres, menor probabilidad tienen los hijos de estar en los cuantiles más bajos.

Sin embargo cabe mencionar que para los cuantiles más altos esto no es tan notorio, pues aquí se hace más uniforme la distribución de
las notas.

En resumen, los promedios más bajos son más probables de encontrar en estudiantes cuyos padres no poseen un alto grado de educación,
sin embargo los promedios más altos si bien en parte siguen una tendencia similar, esta no es tan notoria.
```

# Conclusión
Eso ha sido todo para el lab de hoy, recuerden que el laboratorio tiene un plazo de entrega de una semana. Cualquier duda del laboratorio, no duden en contactarnos por mail o U-cursos.

<p align="center">
  <img src="https://gifdb.com/images/high/orange-cat-cat-walking-with-two-legs-xlgf7qx4i24da74f.gif" width="400">
</p>


<br>
<center>
<img src="https://i.kym-cdn.com/photos/images/original/001/194/195/b18.png" width=100 height=50 />
</center>
<br>

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=87110296-876e-426f-b91d-aaf681223468' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>